### ISSUE TITLE
Header picture

### ISSUE THREAD

**Issue by pr0t00** [studioespresso/wp-clean-content#3]
Hello!
I really like the Theme, and would enjoy it even more, if there is a possibillity to use a picture in the header, instead of the text.

Can you tell me please how to do that?

Best regards,
Olli

**Comment by janhenckens** [comment]
Hey Olli, thanks getting in touch.
An header image option was already on my feature list, I guess I'll bump it up for 1.2 :)
A couple of questions for you if you don't mind... :)
Header image between the menu and the content or above the menu?
The width of the content or next to the menu instead of the title?

Thanks for your feedback!

**Comment by pr0t00** [comment]
Hi Jan, thanks for taking your time!
On your Clean Content GitHub page i saw a picture with how i would really like to have it.
Its on here: https://raw2.github.com/On-Edge/wp-clean-content/develop/screenshot.png

And how did you manage to align the header menu bar to the wordpress site title?

Greetings, Olli

**Comment by janhenckens** [comment]
Hey Oli
That's actually the new header image I'm adding now, it will be in the next version! (which should be ready this week, I'll let you know when it's available)

Cheers!
Jan

**Comment by pr0t00** [comment]
Hi Jan,
perfect. Can't wait to see it! :)

Greetings, Olli

**Comment by janhenckens** [comment]
Hi Oli
Version 1.2 got approved last night so you should be able to update to it and add your header image :)

Enjoy!
Jan

**Comment by pr0t00** [comment]
It is exactly, how i imagined it. Nice:)

But one last thing:
If i use the navigation in the sidebar, and then watch the website in the mobile version, i don't find the  navigation anywhere. Is there something i can do about that?

Cheers Olli

**Comment by janhenckens** [comment]
On mobile (when the screen is narrower then a certain number of pixels), the sidebar gets dropped bellow the main content area. So you should be able to find it at the bottom of the page.

If that's not the case, could you make a new issue for it? (You can do that anyway if you have other questions about this :))
