### ISSUE TITLE
Menu bar icon in mobile view (Android)

### ISSUE THREAD

**Issue by pr0t00** [studioespresso/wp-clean-content#4]
Hi Jan, 

when viewing the website on an Android Smarthphone the icon for the menu bar isn't displayed correctly (haven't checked on a iPhone yet, but on two different Android devices). It seems, like the icon is just missing.

Here is a screenshot:
![2014-05-08 17 08 25](https://cloud.githubusercontent.com/assets/7365706/2917164/b8c85122-d6c2-11e3-9635-74f6151f6b4f.png)

Greeting,

Olli

**Comment by janhenckens** [comment]
That's weird, but the whole site header can still be improved a lot on mobile. I'll try to find an Android device to I can test for myself. I'll keep you posted!
/J

**Comment by janhenckens** [comment]
I've got a fix for this ready, submitting the update to wordpress.org tonight/tomorrow morning. I'll close this issue when it's available for download.

**Comment by janhenckens** [comment]
And approved! You should be able to update to 1.2.1 now :)
