### ISSUE TITLE
Side bar menu in mobile version

### ISSUE THREAD

**Issue by pr0t00** [studioespresso/wp-clean-content#5]
Hi Jan,

in the mobile version the side bar isn't displayed. 
It would be ideal to have it at the end of the site.

Normal view: 
![bildschirmfoto 2014-05-08 um 17 16 10](https://cloud.githubusercontent.com/assets/7365706/2917279/031195da-d6c4-11e3-9dad-391067652913.png)

Mobile view:  
![bildschirmfoto 2014-05-08 um 17 16 22](https://cloud.githubusercontent.com/assets/7365706/2917280/07434c8e-d6c4-11e3-942a-f7def8e3b60f.png)

Greetings,
Olli

**Comment by janhenckens** [comment]
That's what I was expecting it to do too, maybe something broke during one of the last updates. I'll have this fixed in the next version and will let you know when it's done!

Thanks for reporting this!
Cheers
Jan

**Comment by pr0t00** [comment]
Great! Thanks a lot.

Greetings
Olli
