### ISSUE TITLE
Footer text gets cut off in mobile version

### ISSUE THREAD

**Issue by pr0t00** [studioespresso/wp-clean-content#6]
Hi Jan,

ive some more text into the footer,
and when i watch it in the mobile version,
after some lines the text just gets cut off.

Here's a screenshot for that.
![bildschirmfoto 2014-05-16 um 13 23 04](https://cloud.githubusercontent.com/assets/7365706/2996350/d74fd518-dcec-11e3-9da9-04a74cbe4e1b.png)

Greetings
Olli

**Comment by janhenckens** [comment]
Probably before the footer has a max-height set somewhere that shouldn't be there. Looking into it tonight!
