### ISSUE TITLE
Font Use Verdana

### ISSUE THREAD

**Issue by pr0t00** [studioespresso/wp-clean-content#7]
Hi Jan, I hope, you are (all) fine!

I have a question regarding font use in this theme.

For the font i want to use the Verdana, like i still have it on this page http://gespraech.helmutheim.de/ , but want to switch to the new layout. After the update on a testpage, this came out http://testcenter2.hol.es/

Is there a way, to change the fonts back to verdana, to get the old look, but the new features?

I tried it with the following code, but it didn't give me correct result.
- {
  font-family: verdana !important;
  }

Cheers!
Olli

**Comment by janhenckens** [comment]
Hey Olli

You can change the font by editing line 494 of the style.css file. Just remove the 'Avenir Next' so that Veranda is first in line. That should do the trick :)
(the css code do with a fair bit of cleaning up, I'll put that on the list for the next update)

Cheers
/J

**Comment by pr0t00** [comment]
Hi Jan!

I looked it up, but my style.css only looks like in the added screenshots. Do i have to add there also anything?

Thank you!

Olli
![screenshot 2014-09-05 23 04 14](https://cloud.githubusercontent.com/assets/7365706/4171709/4d4f6cf0-3540-11e4-9eb0-4708b9792c57.png)

**Comment by janhenckens** [comment]
Hey Oli, sorry for the late reply! There should be a second file called style.css, but in a folder called "css". There you have to changed the font-family.

Let me know if you have any other questions!
